//! Thin Tauri command adapters.
//!
//! Commands bridge React and the application services. Business logic lives
//! in the modules; commands hold no state of their own.
//!
//! Handlers are registered with their module path so the glue macros
//! generated by `#[tauri::command]` resolve unambiguously.

pub mod audio;
pub mod bible;
pub mod media;
pub mod presentation;
pub mod scripture;
pub mod settings;
pub mod songs;
pub mod speech;

/// Every command handler registered on the Tauri builder.
pub fn all_handlers() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // audio
        audio::list_audio_devices,
        audio::get_default_audio_device,
        audio::start_audio_capture,
        audio::stop_audio_capture,
        audio::get_audio_capture_state,
        // speech
        speech::get_speech_state,
        speech::start_listening,
        speech::stop_listening,
        speech::start_audio_pipeline,
        speech::stop_audio_pipeline,
        // scripture
        scripture::detect_scripture,
        // bible
        bible::list_bible_translations,
        bible::list_translation_catalogue,
        bible::add_translation,
        bible::update_translation,
        bible::delete_translation,
        bible::list_books,
        bible::get_passage,
        bible::search_bible,
        bible::suggest_bible_topics,
        bible::save_custom_verses,
        bible::set_default_translation,
        bible::import_bible_translation,
        bible::import_sqlite_bible_translation,
        // presentation
        presentation::get_presentation_state,
        presentation::project_text,
        presentation::project_passage,
        presentation::clear_presentation,
        presentation::open_presentation_window,
        presentation::close_presentation_window,
        presentation::set_presentation_display,
        presentation::set_fullscreen,
        presentation::list_displays,
        presentation::list_presentations,
        presentation::get_presentation,
        presentation::create_presentation,
        presentation::delete_presentation,
        presentation::add_presentation_item,
        presentation::update_presentation_item,
        presentation::remove_presentation_item,
        presentation::project_saved_item,
        presentation::project_saved_presentation,
        presentation::show_next_item,
        presentation::show_previous_item,
        // media
        media::list_media,
        media::import_media,
        media::remove_media,
        media::browse_directory,
        media::load_media_directory,
        media::project_media,
        media::get_media_playback_state,
        media::control_media_playback,
        media::report_media_playback,
        // songs
        songs::list_songs,
        songs::get_song,
        songs::save_song,
        songs::delete_song,
        songs::project_song,
        // settings
        settings::get_settings,
        settings::update_settings,
        settings::get_setup_state,
        settings::complete_setup,
    ]
}
